<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>RecortadorDeVideos.UI</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\app.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RecortadorDeVideos.Domain\RecortadorDeVideos.Domain.csproj" />
    <ProjectReference Include="..\RecortadorDeVideos.Application\RecortadorDeVideos.Application.csproj" />
    <ProjectReference Include="..\RecortadorDeVideos.Infrastructure\RecortadorDeVideos.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

</Project>
